"""
Alert Collector.
Responsible for monitoring Suricata alerts and pulling from Elasticsearch.
"""

import logging
import threading
from typing import List, Dict, Any

from .config_manager import FrameworkConfig

class AlertCollector:
    """Collects and filters alerts generated by Suricata."""

    def __init__(self, config: FrameworkConfig):
        """
        Initialize the AlertCollector.
        
        Args:
            config: Framework configuration.
        """
        self.config = config
        self.logger = logging.getLogger(__name__)
        self._is_collecting = False
        self._collected_alerts: List[Dict[str, Any]] = []
        self._collection_thread = None

    def start_collection(self) -> None:
        """Starts the background process of monitoring for alerts."""
        if self._is_collecting:
            return
            
        self.logger.info("Starting alert collection.")
        self._is_collecting = True
        self._collected_alerts = []
        
        # Start a mock monitoring thread for now (Phase 4 will implement real Suricata reading)
        self._collection_thread = threading.Thread(target=self._monitor_loop)
        self._collection_thread.daemon = True
        self._collection_thread.start()

    def stop_collection(self) -> None:
        """Stops the background alert monitoring process."""
        self.logger.info("Stopping alert collection.")
        self._is_collecting = False
        if self._collection_thread:
            self._collection_thread.join(timeout=2)

    def _monitor_loop(self) -> None:
        """Background loop to read from eve.json or Elasticsearch."""
        while self._is_collecting:
            # TODO: Phase 4 & 5 integration (read from eve.json and ES)
            import time
            time.sleep(1)

    def get_alerts_since(self, timestamp: float) -> List[Dict[str, Any]]:
        """
        Retrieves alerts generated since the given timestamp.
        
        Args:
            timestamp: Unix timestamp.
            
        Returns:
            List of alert dictionaries.
        """
        # Filter collected alerts by timestamp
        return [alert for alert in self._collected_alerts if alert.get("timestamp", 0) >= timestamp]
